#you can use variable also 
cc=clang


# for running this file use the command: make hello in this directory
hello: hello.c test.o
	$(cc) -o hello hello.c
test.o: test.c
	$(cc) -c test.c -o test.o

clean:
	rm -f hello test.o